name: mgenware_dart_lints
description: Dart lint rules used in Mgenware.
version: 8.1.0
homepage: https://github.com/mgenware/mgenware_dart_lints

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  lints: ^6.0.0
  flutter_lints: ^6.0.0
